// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsRVdtAc0g90TOPQpxj3V6dFNnYgQVItk',
    appId: '1:150905737389:android:04e4da87ecb00386e03624',
    messagingSenderId: '150905737389',
    projectId: 'quizz-app-flutter-e9d37',
    storageBucket: 'quizz-app-flutter-e9d37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQAmWFfrR_r0dayu5KvOY3JLnqfkhlFvA',
    appId: '1:150905737389:ios:6ac91b25b8a16b2be03624',
    messagingSenderId: '150905737389',
    projectId: 'quizz-app-flutter-e9d37',
    storageBucket: 'quizz-app-flutter-e9d37.appspot.com',
    androidClientId: '150905737389-75rucdiiuhl5cf31ik2geqj6k11p29m1.apps.googleusercontent.com',
    iosClientId: '150905737389-8lugkhm33ugkkcaqkehktgvm5356n7ea.apps.googleusercontent.com',
    iosBundleId: 'com.gaeldev.learningapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQAmWFfrR_r0dayu5KvOY3JLnqfkhlFvA',
    appId: '1:150905737389:ios:6ac91b25b8a16b2be03624',
    messagingSenderId: '150905737389',
    projectId: 'quizz-app-flutter-e9d37',
    storageBucket: 'quizz-app-flutter-e9d37.appspot.com',
    androidClientId: '150905737389-75rucdiiuhl5cf31ik2geqj6k11p29m1.apps.googleusercontent.com',
    iosClientId: '150905737389-8lugkhm33ugkkcaqkehktgvm5356n7ea.apps.googleusercontent.com',
    iosBundleId: 'com.gaeldev.learningapp',
  );
}
